version: '3'
services:
  oh-eth:
    build: 
      context: .
      dockerfile: ./main/docker/Dockerfile
    image: oh-eth
    container_name: oh-eth
    ports:
    - "8080:8080"
    links:
    - redis
  redis:
    image: redis
    ports:
    - "6379:6379"
    container_name: redis
