version: 2
jobs:
  build:
    working_directory: ~/overhide-ethereum
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run:
          shell: /bin/sh
          command: touch .npmrc.dev
      - run:
          shell: /bin/sh
          command: mkdir test-report          
      - run:
          shell: /bin/sh
          command: docker-compose -f main/docker/docker-compose.yml -f main/docker/docker-compose.dev.yml --project-directory . --project-name oh run -e ETHERSCAN_KEY -e ETHERSCAN_TYPE -v test-report:/home/node/app/test-report oh-eth npm run test-report
      - store_test_results:
          path: ./test-report
      - store_artifacts:
          path: ./test-report