version: 2
jobs:
  build:
    working_directory: ~/overhide-ethereum
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run:
          command: |
            printf "DEBUG=overhide-ethereum:*,-overhide-ethereum:is-signature-valid:txs,-overhide-ethereum:get-transactions:txs" > .npmrc.dev
            printf "\n" >> .npmrc.dev
            printf $ETHERSCAN_KEY >> .npmrc.dev
            printf "\n" >> .npmrc.dev
            printf $ETHERSCAN_TYPE >> .npmrc.dev
      - run:
          command: |
            docker-compose -f main/docker/docker-compose.yml -f main/docker/docker-compose.dev.yml -f main/docker/docker-compose.test.yml --project-directory . --project-name oh up
      - store_test_results:
          path: ./test-report
      - store_artifacts:
          path: ./test-report